### ISSUE TITLE
Issue with ~na spells (Poisona, Paralyna, etc)

### ISSUE THREAD

**Issue by Watercrown** [ThornyFFXI/tCrossBar#1] opened 2023-03-01 18:04 UTC
Hey. 

I noticed a bug. It seems like any ~na spells are automatically faded (as if they were on cooldown). I noticed it while mapping my WHM macros. Seems to be the only ones I've run into so far with this issue.

**Comment by ThornyFFXI** [comment] 2023-03-01 22:00
If possible, please verify:
-server(if retail can just say retail, don't need to know which)
-main job and level
-sub job and level

I will look into this tomorrow morning.

**Comment by Watercrown** [comment] 2023-03-01 23:16
Hey.

HorizonXI
WHM lv25/BLM lv 12

**Comment by Watercrown** [comment] 2023-03-02 03:16
I've been doing my RDM bindings. I notice the same issue with Dispel and Sleep II. I tried it with different targeting types (st, stnpc) and it's the same.

**Comment by ThornyFFXI** [comment] 2023-03-02 14:28
I've found the cause of this, it should be resolved in an update later this morning.  You shouldn't have to redo your bindings or anything, once it's done updating the addon will correct the issue.

**Comment by ThornyFFXI** [comment] 2023-03-02 16:28
This should be resolved in 1.01.

**Closed by ThornyFFXI** 2023-03-02 16:28 UTC
